[package]
name = "safer-ffi-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
safer-ffi = { version = "0.1.13", features = ["proc_macros"] }

[build-dependencies]
safer-ffi-gen = "0.9.2"
