/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_SAFER_FFI_EXAMPLE__
#define __RUST_SAFER_FFI_EXAMPLE__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** <No documentation available> */
typedef struct Todo {
    /** <No documentation available> */
    int32_t id;

    /** <No documentation available> */
    char * note;
} Todo_t;

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_Todo {
    /** <No documentation available> */
    Todo_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_Todo_t;

/** <No documentation available> */
typedef struct App {
    /** <No documentation available> */
    Vec_Todo_t todos;
} App_t;


#include <stdbool.h>

/** <No documentation available> */
bool
add_todo (
    App_t * app,
    int32_t id,
    char const * note);

/** <No documentation available> */
void
app_free (
    App_t * _app);

/** <No documentation available> */
App_t *
app_new (void);

/** <No documentation available> */
size_t
get_todo_count (
    App_t const * app);

/** <No documentation available> */
int32_t
get_todo_id_at (
    App_t const * app,
    size_t index);

/** <No documentation available> */
char *
get_todo_note_at (
    App_t const * app,
    size_t index);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_SAFER_FFI_EXAMPLE__ */
